/* Generated by           cobc 3.2.0 */
/* Generated from         COBOL\treino.cbl */
/* Generated at           Sep 22 2025 13:00:32 */
/* GnuCOBOL build date    Jul 28 2023 19:10:09 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\ProgramData\chocolatey\lib\gnucobol\tools\bin\cobc.exe -x -ftraceall -g -std=default -ext cpy -ext cbl -ext cob -I . COBOL\treino.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {24, (cob_u8_ptr)"HELLO, COBOL NO VS CODE!", &a_1};


/* Strings */
static const char st_1[]	= "HELLO";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"COBOL\\treino.cbl"};

#define cob_nop	if (!module) cob_nop

